### ISSUE TITLE
Participants placed in groups of 1 (Docker, demo config files)

### ISSUE THREAD

**Issue by kborash** [virtualcommons/foraging#36]
I've been unable to get the demo configuration files and the docker setup included in the repository to work properly. Whenever we run the facilitator and connect to it with 5 clients, each client is placed in it's own harvesting group instead of all competing on the same board. The initial practice round and questions seems to work fine.

We've tried setting clients-per-group and removing that configuration value (as 5 appears to be the default group size in the code).

I know it's loading the configuration files correctly since other changes I've tried, like board size, are reflected in the clients. Any help or advice you could provide would be really appreciated. It's entirely possible I'm misunderstanding what the demo files are supposed to produce.

**Comment by alee** [comment]
Thanks for letting me know! I've updated the demo configuration files so group rounds should now be group rounds again. I made a change to the group partitioning logic that didn't get propagated to the demo configuration files.
